server:
  port: 5000
spring:
  application:
    name: service-zuul
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-r:
      path: /api-r/**
      service-id: service-ribbon
    api-h:
      path: /api-h/**
      service-id: service-home