server:
  port: 8761
spring:
  application:
    name: eureka-server
  profiles: track1
eureka:
  client:
    service-url:
      defaultZone: http://track2:8769/eureka/
  instance:
    hostname: track1
---
server:
  port: 8769
spring:
  application:
    name: eureka-server
  profiles: track2
eureka:
  client:
    service-url:
      defaultZone: http://track1:8761/eureka/
  instance:
    hostname: track2