server:
  port: 7000
spring:
  application:
    name: service-ribbon
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/